//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HidrometroApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ConsumoDiario
    {
        public long IdConsumoDiario { get; set; }
        public long? IdPerfil { get; set; }
        public DateTime? DataConsumo { get; set; }
        public decimal? M3Consumidos { get; set; }

        public virtual Perfil Perfil { get; set; }
    }
}
