//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HidrometroApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HIDROVIVAEntities : DbContext
    {
        public HIDROVIVAEntities()
            : base("name=HIDROVIVAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConsumoDiario> ConsumoDiario { get; set; }
        public virtual DbSet<ConsumoMensal> ConsumoMensal { get; set; }
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<Instalacao> Instalacao { get; set; }
        public virtual DbSet<ParametroSistema> ParametroSistema { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Taxas> Taxas { get; set; }
        public virtual DbSet<Telefone> Telefone { get; set; }
    }
}
