//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HidrometroApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Instalacao
    {
        public Instalacao()
        {
            this.Perfil = new List<Perfil>();
        }

        public long IdInstalacao { get; set; }
        public decimal? NumeroMoradores { get; set; }
        public DateTime? TempoPermanenciaDiaria { get; set; }
        public decimal? MediaConsumoDiario { get; set; }
        public string ApelidoInstalacao { get; set; }
        public Nullable<int> InstalacaoUsoComum { get; set; }
        public decimal? InstalacaoAtiva { get; set; }

        public virtual ICollection<Perfil> Perfil { get; set; }
    }
}
