//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HidrometroApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroSistema
    {
        public long IdParametro { get; set; }
        public long? IdTaxa { get; set; }
        public decimal? QtdInstalacoes { get; set; }
        public decimal? MetaDeConsumoIndividual { get; set; }
        public decimal? ValorParaAlerta { get; set; }
    
        public virtual Taxas Taxas { get; set; }
    }
}
