//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HidrometroApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Perfil
    {
        public Perfil()
        {
            this.ConsumoDiario = new List<ConsumoDiario>();
        }

        public long IdPerfil { get; set; }
        public long? IdPessoa { get; set; }
        public long? IdInstalacao { get; set; }
        public Nullable<int> TipoPerfil { get; set; }
        public Nullable<int> PerfilAtivo { get; set; }

        public virtual ICollection<ConsumoDiario> ConsumoDiario { get; set; }
        public virtual Instalacao Instalacao { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
