//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HidrometroApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Taxas
    {
        public Taxas()
        {
            this.ParametroSistema = new List<ParametroSistema>();
        }

        public long IdTaxa { get; set; }
        public decimal? Valor { get; set; }
        public DateTime? DataInicioVigencia { get; set; }
        public DateTime? DataFimVigencia { get; set; }
        public decimal? QuantidadeMinimaM3 { get; set; }
        public string QuantidadeMaximaM3 { get; set; }

        public virtual ICollection<ParametroSistema> ParametroSistema { get; set; }
    }
}
